name: LearnPythonforResearch

dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - bokeh
  - deepdish
  - qgrid
  - ipywidgets
  - requests
  - lxml
  - cssselect
  - xlrd
  - openpyxl
  - seaborn
  - pip:
    - requests-html